### ISSUE TITLE
Training with extended chord vocabulary

### ISSUE THREAD

**Issue by Schran4er** [dvruette/figaro#5]
I am trying to train FIGARO with an extended chord vocabulary (using the provided checkpoints).

I edited `get_chord_tokens(...)` in `vocab.py` to match the chord qualities in my dataset. However, when loading the checkpoint, I ran into the error of size missmatch for `in_layer.weight` and `out_layer.weight` - obviously, as the vocabulary changed. 
Do you happen to know which additional steps are needed to continue training from the existing checkpoints, with a dataset that contains more chord qualities than the ones from the paper?

Thank you in advance!

**Comment by dvruette** [comment]
I see, this is going to require some model surgery, but it's definitely possible. You'll have to add new rows to the embedding and output layers such that the shapes are `(new_vocab_size, d_model)` and `(d_model, new_vocab_size)` respectively. The code for this is going to look something along the lines of:

```python
layer = get_embedding_layer(...)
old_weights = layer.weight.data
new_weights = nn.Embedding(new_vocab_size, d_model).weight.data
new_weights[:old_weights.size(0)] = old_weights
layer.weight.data.set_(new_weights)
```

Note that this assumes that tokens from the old vocabulary have the same index in the new vocabulary. If you're simply adding the new tokens to the `get_chord_tokens` function, this might not be the case. In that case, you'll have to build a mapping from old to new indices and initialize the `new_weights` accordingly.

**Comment by Schran4er** [comment]
Thanks again for your quick response.

I understand why it is `new_weights = nn.Embedding(new_vocab_size, d_model).weight.data` for the `in_layer`. 
But - just to verify that I understand it correctly - it is `new_weights = nn.Linear(new_vocab_size, d_model).weight.data` for the `out_layer` isn't it?

**Comment by dvruette** [comment]
Pretty sure the shape should be transposed, i.e. `new_weights = nn.Linear(d_model, new_vocab_size).weight.data`, but essentially yes.
