### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'vae_run'

### ISSUE THREAD

**Issue by Wietc** [dvruette/figaro#8]
When I try to generate midi from the command:
`python src/generate.py --model figaro --checkpoint ./checkpoints/figaro.ckpt --vae_checkpoint ./checkpoints/vq-vae.ckpt`
The issue can be repeated.
And I am sure that the version of every packages I downloaded are correct.

**Comment by dvruette** [comment]
What’s the error message you’re getting? I can take a look if I know what I’m looking for.

**Comment by Wietc** [comment]
`Traceback (most recent call last):
  File "/home/jiatao/myprogram/figaro/src/generate.py", line 201, in <module>
    main()
  File "/home/jiatao/myprogram/figaro/src/generate.py", line 154, in main
    model, vae_module = load_model(args.checkpoint, args.vae_checkpoint)
  File "/home/jiatao/myprogram/figaro/src/generate.py", line 71, in load_model
    model = load_old_or_new_checkpoint(Seq2SeqModule, checkpoint)
  File "/home/jiatao/myprogram/figaro/src/generate.py", line 44, in load_old_or_new_checkpoint
    model = model_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'vae_run'`

it is the error message in detail

And I check my package version by using `pip list`
Package             Version
------------------- ----------
aiohttp             3.9.3
aiosignal           1.3.1
async-timeout       4.0.3
attrs               23.2.0
Brotli              1.0.9
certifi             2024.2.2
charset-normalizer  2.0.4
filelock            3.13.1
frozenlist          1.4.1
fsspec              2024.2.0
gmpy2               2.1.2
huggingface-hub     0.21.4
idna                3.4
Jinja2              3.1.3
lightning-utilities 0.10.1
MarkupSafe          2.1.3
mido                1.3.2
mkl-fft             1.3.8
mkl-random          1.2.4
mkl-service         2.4.0
mpmath              1.3.0
multidict           6.0.5
networkx            3.1
numpy               1.26.4
packaging           23.2
pillow              10.2.0
pip                 23.3.1
pretty-midi         0.2.10
PySocks             1.7.1
pytorch-lightning   2.1.4
PyYAML              6.0.1
regex               2023.12.25
requests            2.31.0
safetensors         0.4.2
setuptools          68.2.2
six                 1.16.0
sympy               1.12
tokenizers          0.15.2
torch               2.1.1
torchaudio          2.1.1
torchdata           0.7.1
torchmetrics        1.3.1
torchtext           0.16.2
torchvision         0.16.1
tqdm                4.66.2
transformers        4.37.2
triton              2.1.0
typing_extensions   4.9.0
urllib3             2.1.0
wheel               0.41.2
yarl                1.9.4

**Comment by dvruette** [comment]
I've finally gotten around to taking a look at this, seems like the fix was quite simple. Let me know if everything works now for you!
